variables:
    GIT_SUBMODULE_STRATEGY: recursive

image: python:2.7

build:
    script:
    - wget https://sourceforge.net/projects/scons/files/scons/3.0.0/scons-3.0.0.tar.gz
    - tar xzf scons-3.0.0.tar.gz
    - python scons-3.0.0/script/scons --unit-test