variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
    script:
    - apk add --no-cache build-base
    - apk update && apk add ca-certificates && update-ca-certificates && apk add openssl
    - apk add --update python python-dev py-pip build-base && pip install virtualenv && rm -rf /var/cache/apk/*
    - wget https://sourceforge.net/projects/scons/files/scons/3.0.0/scons-3.0.0.tar.gz
    - tar xzf scons-3.0.0.tar.gz
    - python scons-3.0.0/script/scons --unit-test

test:
    script:
    - Warmup/A_Very_Big_Sum/build/A_Very_Big_Sum',
    - Warmup/Diagonal_Difference/build/Diagonal_Difference',
    - Warmup/Plus_Minus/build/Plus_Minus',
    - Warmup/Staircase/build/Staircase',
    - Warmup/Time_Conversion/build/Time_Conversion',    
    - Warmup/Circular_Array_Rotation/build/Circular_Array_Rotation',
    - Sorting/The_Full_Counting_Sort/build/The_Full_Counting_Sort',
    - Sorting/Closest_Numbers/build/Closest_Numbers',
    - Sorting/Find_the_Median/build/Find_the_Median',
    - Sorting/Insertion_Sort_Advanced_Analysis/build/Insertion_Sort_Advanced_Analysis',