# This file is licensed under the MIT License.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

import os
import json
import sys
import glob

env = Environment();

env.VariantDir('build', 'src', duplicate=0)
files = ["build/main.cpp"]
prog = env.Program("build/A_Very_Big_Sum", files)

test = Command( target = "test/output.txt",
                source = prog,
                action = prog[0].abspath + " > $TARGET" )

AlwaysBuild( test )
